### ISSUE TITLE
Is this config still useable?

### ISSUE THREAD

**Issue by Zabooby** [Argon-/mpv-config#17]
The last changes were a over a year ago has this config been abandoned and is it still useable with all the updates to mpv as well as the scripts and shaders it uses?

**Comment by chromer030** [comment]
Some changes is needed but overall it's still useable.

**Comment by Zabooby** [comment]
Apart from updating scripts and shaders, are there any other changes you recommend?

**Comment by chromer030** [comment]
Adding new flags from https://mpv.io/manual/stable/

**Comment by Argon-** [comment]
I actively use it. Just after some time of experimenting you "settle" on what you think is best. Also I usually don't push every small change but wait until a certain amount of difference accumulated because those changes are often just subjective little things that often change back and forth depending on my mood.
But then, I haven't upgraded mpv in a couple of months so I can't guarantee that something on the mpv end of things changed. mpv releases are fairly slow (which I appreciate) and rarely break things. I'm on vacation right now but once home I'll check if I have unpushed changes/fixes.
