### ISSUE TITLE
i'm having issues with OSC

### ISSUE THREAD

**Issue by SolarAquarion** [Argon-/mpv-config#4]
![screenshot from 2016-07-26 18-04-57](https://cloud.githubusercontent.com/assets/5307016/17157156/96cb7406-535b-11e6-9e21-9f9ac646ce93.png)
![screenshot from 2016-07-26 18-04-00](https://cloud.githubusercontent.com/assets/5307016/17157155/96ca55c6-535b-11e6-80c1-54bd87af06e6.png)

i think the second one is my edit of your config, and the first one is vanilla mpv

**Comment by Argon-** [comment]
My OSC config looks totally different.
There are two possibilities:
- your mpv installation is broken -> mpv issue tracker (it should never look like in your image)
- you changed stuff and/or are using some options wrong -> it is not caused by "my" config -> mpv issue tracker  
  (and I don't even know what you did/changed)
