### ISSUE TITLE
Some files are just links, not real files.

### ISSUE THREAD

**Issue by Yuki-Judai** [Argon-/mpv-config#9]
/scripts/
auto-profiles.lua | mines.lua | repl.lua | stats.lua

And

/shaders/
adaptive-sharpen.glsl | FineSharp.glsl | SSimSuperRes.glsl

nnedi3-nns32-win8x4-yuv.hook | nnedi3-nns32-win8x4.hook | nnedi3-nns64-win8x4-yuv.hook | nnedi3-nns64-win8x4.hook

These files are just replacement links, not real files. Could you upload those files? Thanks.

**Comment by Argon-** [comment]
These files are all inside other repos that reside in the same directory. Because they are git repos themselves, github doesn't upload them, not much I can do. But you can always just go to these repos directly, e.g. 
https://github.com/wm4/mpv-scripts
https://github.com/rossy/mpv-repl
Shaders: https://github.com/mpv-player/mpv/wiki/User-Scripts#pixel-shaders

**Comment by Yuki-Judai** [comment]
I see. I have used your configuration files for a long time and they just work fine. Thank you for sharing them. :-)

**Comment by linzack** [comment]
Hi, TIL you can use
`git clone --recurse-submodules -j8 https://github.com/Argon-/mpv-config`
to clone submodule too, then the symbolic link like 'repl.lua' can be resolved!

But you will need to set private ssh key with your github account, or you'll get `Host key verification failed` and github refuse to clone submodule.

The [detailed document is here](https://help.github.com/enterprise/11.10.340/user/articles/generating-ssh-keys/), after the process, you can test with `ssh -T git@github.com`, 
shall get `Hi yourname! You've successfully authenticated`, 
otherwise it's `Permission denied (publickey)`

Thank you for the mpv config!!

**Comment by linzack** [comment]
Hi, 
I still got some strange errors, when mpv play video the console (cygwin on win10) shows 
```
     mines:
     mines: stack traceback:
     mines:     [C]: at 0x0041b4a0
     mines: Lua error: C:\Users\usr\AppData\Roaming/mpv/scripts/mines.lua:1: unexpected symbol near '!'
```
It seems like mpv can't read "mines.lua", even the file existed (symbolic link)
```
$ ls -al "C:\Users\usr\AppData\Roaming/mpv/scripts/mines.lua"
lrwxrwxrwx 1 usr None 21 Oct 21 14:56 'C:\Users\usr\AppData\Roaming/mpv/scripts/mines.lua' -> mpv-scripts/mines.lua
```
but if I replace symbolic link with the real file, _the error disappear_
```
$ mv mines.lua mines.lua.bak
$ cp mpv-scripts/mines.lua .
$ ls -la
-rwx------+ 1 usr None 9698 Oct 21 17:14 mines.lua
lrwxrwxrwx  1 usr None   21 Oct 21 14:56 mines.lua.bak -> mpv-scripts/mines.lua
```
if I test lua, it can read file through symbolic link though
```
// real file
$ lua mines.lua
lua: mines.lua:1: module 'mp.assdraw' not found:
        no field package.preload['mp.assdraw']
stack traceback:
        [C]: in function 'require'
        mines.lua:1: in main chunk
        [C]: in ?

// symbolic link 
$ lua mines.lua.bak
lua: mines.lua.bak:1: module 'mp.assdraw' not found:
        no field package.preload['mp.assdraw']
stack traceback:
        [C]: in function 'require'
        mines.lua.bak:1: in main chunk
        [C]: in ?
```
dunno what happened here lol, maybe something is wrong in the mpv build in lua?

**Comment by chros73** [comment]
> These files are all inside other repos that reside in the same directory.

Hi!
Can you upload the FineSharp.glsl into the repo because it's no longer available on mpv wiki page.
Thanks!
